<?php

define('REPOSITORY_HOST', $_ENV['REPOSITORY_HOST']);
define('REPOSITORY_DATABASE', $_ENV['REPOSITORY_DATABASE']);
define('REPOSITORY_USER', $_ENV['REPOSITORY_USER']);
define('REPOSITORY_PASSWORD', $_ENV['REPOSITORY_PASSWORD']);
define('REPOSITORY_SIGNATURE', $_ENV['REPOSITORY_SIGNATURE']);

define('JWT_KEY', $_ENV['AUTH_JWT_KEY']);
define('JWT_ISS', $_ENV['AUTH_JWT_ISS']);
define('JWT_AUD', $_ENV['AUTH_JWT_AUD']);
define('JWT_IAT', $_ENV['AUTH_JWT_IAT']);
define('JWT_NBF', $_ENV['AUTH_JWT_NBF']);
define('JWT_ALGORITHM', $_ENV['AUTH_JWT_ALGORITHM']);

define('VENDOR_PATH', $_ENV['AUTH_VENDOR_PATH']);